version: '2.2'
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '8000:8000'
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./client/node_modules
    stdin_open: true
    tty: true